### ISSUE TITLE
Не работает сортировка блюд

### ISSUE THREAD

**Issue by SilurK** [SilurK/DreamTeam#1]
### При нажатии на кнопку сортировки программа аварийно завершается, при предварительном анализе кода, было обнаружено, что выбрасывается исключение [`std::bad_alloc.`](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=2ahUKEwj836H6kqzoAhWH0KYKHSlqANwQFjACegQIBBAB&url=https%3A%2F%2Fen.cppreference.com%2Fw%2Fcpp%2Fmemory%2Fnew%2Fbad_alloc&usg=AOvVaw0LgejqU-2XQQg_YTvzoPJ7)

**Comment by OlyaBershka** [comment]
### Ошибка была исправлена.
